insert into tb_usuario values(nextval('sq_usuario'), 'teste','teste','teste',current_date,current_timestamp); 
insert into tb_usuario values(    nextval('sq_usuario'),    'Carla Louise da Rocha',    'carla_louise_darocha@mundivox.com.br',    '5YKUEmmHXW',    '1996-07-01',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Thomas Ruan Benício Farias',    'thomas-farias80@facebook.com',    '0ctdOMUd0d',    '1981-02-26',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Alana Tereza Clara Freitas',    'alana-freitas71@stembalagens.com.br',    'BCGK695qhT',    '1945-05-21',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Ruan Ryan Rezende',    'ruan-rezende84@comercialrizzo.com',    '5Sc1zFhyij',    '1965-05-08',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Isabel Camila Sara Martins',    'isabel_camila_martins@julietavinhas.fot.br',    'XqiFx4Zjt2',    '1975-02-11',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Gabriel Severino Moura',    'gabriel.severino.moura@grupoaerius.com.br',    's71l4tanBr',    '2001-01-23',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Sueli Analu Duarte',    'sueli_analu_duarte@zuinzuin.com.br',    'BiYAniYeYh',    '1982-01-17',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Nicole Isis Nascimento',    'nicole.isis.nascimento@ozsurfing.com.br',    'USH8JwQtIA',    '1950-07-02',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Mirella Benedita Aragão',    'mirellabeneditaaragao@clickfios.com.br',    'XRuMS9hY9R',    '1965-08-04',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Mário Renan Anderson Silva',    'mariorenansilva@expressoforte.com.br',    'D3NAP7dax6',    '1988-04-17',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Bento Yago Rocha',    'bento.yago.rocha@yahoo.com .br',    'CiXJTeW75U',    '1988-07-14',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Eduardo Raimundo da Costa',    'eduardo-dacosta85@artedaserra.com.br',    'PjFzN4dXSM',    '1947-01-25',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Juan Raimundo Enrico Pereira',    'juan_raimundo_pereira@luxafit.com.br',    'tHH3ac1Jy9',    '1963-07-12',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Kevin Nicolas da Luz',    'kevin-daluz76@trt15.jus.br',    'pXbKu04zKk',    '1998-06-01',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Lívia Priscila Tereza de Paula',    'livia_priscila_depaula@inepar.com.br',    'jucNaRr0KG',    '1976-03-25',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Emilly Sônia Baptista',    'emillysoniabaptista@destaco.com',    '0OPOIunaqB',    '1977-04-17',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Joaquim Augusto Fogaça',    'joaquim-fogaca73@cntbrasil.com.br',    'Ikmx0WPlhA',    '2004-04-01',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Rebeca Priscila da Mata',    'rebeca.priscila.damata@etirama.com.br',    'lchl783kpR',    '1981-02-11',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Renan Eduardo Samuel Figueiredo',    'renaneduardofigueiredo@outloock.com',    'qW91oyRMO0',    '1976-01-27',    current_timestamp);
insert into tb_usuario values(    nextval('sq_usuario'),    'Jorge Otávio Raul Assis',    'jorge_assis@fulltransport.com.br',    'ZK4uH5qDhz',    '1988-06-26',    current_timestamp);
